# Generated by Django 4.2.2 on 2023-06-13 18:04

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Applicable'), (2, 'Retired')], default=0)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('name', models.SlugField(max_length=8)),
                ('desc', models.TextField()),
                ('pilots', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Process',
                'permissions': [('is_qm', 'Quality manager')],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='process',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 1)), fields=('name',), name='process_name'),
        ),
        migrations.AddConstraint(
            model_name='process',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date')), ('end_date', None), _connector='OR'), name='process_dates'),
        ),
    ]
